### ISSUE TITLE
Shop Readability

### ISSUE THREAD

**Issue by SageRLee** [SageRLee/groupproject-team-1-b-aj#2]
The shop currently has a white background, making the yellow text of current gold hard to read. In addition, the price of each card is not visible, forcing players to guess the true price. 
The background will be added in shoptest.java. While code is present for implementing a background, it is currently non-functional and must be fixed. During initialization of the object, the correct image for a background will be loaded, and then turned off when the player leaves the menu. 

In the same object, a text object will be displayed showing the price of the selected card. If no card is selected, it will become invisible. In the mousePressed method, the program will check if a card is selected, displaying the correct price if so.

**Comment by onzfonz** [comment]
I would like for you to make this dynamic, by having all the text and prices and item names for the shop in a file that the store then reads in. This would allow you to change the shop without having to change the code (just change the text file)
Let me know if you have any questions about it but yeah 🚀
